language: java
jdk: oraclejdk8
os: linux
sudo: false

script: mvn --show-version --errors --batch-mode clean verify

after_success: mvn clean cobertura:cobertura coveralls:report

cache:
  directories:
   - $HOME/.m2
